### ISSUE TITLE
Can you add a License

### ISSUE THREAD

**Issue by nowells** [mbilokonsky/bash-color#1]
Hi Mykola!

Thank you for your OSS contributions! We use your library at my company, but they need for us to know what License you are releasing this software as. Would you be willing to add a license to your `package.json` or in your `README.md`? I have personally always released my software under `MIT`, but obviously use whatever license you prefer, we just need to know what you have chosen so we can continue to use your software.

If you can provide information about if the license you choose applied to your previously released versions as well (and not just going forward) that would be awesome.

Thank you for your consideration!

Cheers,
Nowell

**Comment by mbilokonsky** [comment]
No problem, I've added an MIT license file and added MIT to the
package.json. Let me know if that's sufficient or if you'd like me to do
anything else!

**Comment by nowells** [comment]
@mbilokonsky you are wonderful! Thank you for being so responsive. Can you indicate here if you are OK applying this MIT license to previously released versions as well?

**Comment by mbilokonsky** [comment]
Yes this license applies retroactively and any version of this software
predating the addition of this license should be considered free to use
under the same terms.

**Comment by nowells** [comment]
@mbilokonsky thank you so much for being so responsive and helpful! Could I bother you again to ask that you publish the new licensed version to npm? ❤️

**Comment by mbilokonsky** [comment]
I knew I was forgetting something! 0.0.4 has been published. Thanks for the feedback!
